server.port=8080
server.servlet.context-path=/foodara

spring.application.name=foodara
spring.datasource.url=jdbc:postgresql://${POSTGRESQL_DB_IP}:${POSTGRESQL_DB_PORT}/foodara?options=-c%20timezone=Asia/Ho_Chi_Minh
spring.datasource.username=${POSTGRESQL_DB_USERNAME}
spring.datasource.password=${POSTGRESQL_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
