server.port=8083
server.servlet.context-path=/api
spring.application.name=foodara-payment-service

# SpringDoc Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# SePay Webhook — only secret key needed
app.sepay.secret-key=${SEPAY_SECRET_KEY:}

# Main Backend URL for Internal Callbacks
app.main-backend.url=${MAIN_BACKEND_URL:http://localhost:8080/api}
